const apiConstants = {

    UPDATE_LIST: "UPDATE_LIST",
    UPDATE_LIST_SUCCESS: "UPDATE_LIST_SUCCESS",
    UPDATE_LIST_FAIL: "UPDATE_LIST_FAIL",

    HANDLE_SEARCH: "HANDLE_SEARCH",
    HANDLE_SEARCH_SUCCESS: "HANDLE_SEARCH_SUCCESS",
    HANDLE_SEARCH_FAIL: "HANDLE_SEARCH_FAIL",

    UPDATE_VIEW: "UPDATE_VIEW",
    UPDATE_VIEW_SUCCESS: "UPDATE_VIEW_SUCCESS",
    UPDATE_VIEW_FAIL: "UPDATE_VIEW_FAIL"
}
export default apiConstants;
